[[redirects]]
from = "https://vtange.net"
to = "https://vtange.com"
status = 301

[[redirects]]
from = "https://www.vtange.net"
to = "https://www.vtange.com"
status = 301

[[redirects]]
from = "https://vtange.net/*"
to = "https://vtange.com"
status = 301

[[redirects]]
from = "https://www.vtange.net/*"
to = "https://www.vtange.com"
status = 301